version: "3.5"

services:
  cov19stat:
    build:
      dockerfile: Dockerfile
      context: .
    image: ondrno/cov19stats:${COV19_VERSION:-latest}
    container_name: cov19stats
    ports:
    - 8050:8050
    restart: always
    volumes:
      - ./log:/app/log
