# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        python -m pytest tests
    - name: URLs-checker
      uses: urlstechie/URLs-checker@0.1.6
      with:
        # A project to clone. If not provided, assumes already cloned in the present working directory.
        git_path: # optional
        # If a project (git_path) is defined, use this branch. Defaults to master
        branch: # optional, default is master
        # Cleanup (delete) repository to check after doing so (appropriate for when clone is done)
        cleanup: # optional
        # A comma-separated list of file types to cover in the URL checks
        file_types: # optional, default is .md,.py,.rst,.html
        # Choose whether to include file with no URLs in the prints.
        print_all: # optional
        # If a request fails, retry this number of times. Defaults to 1
        retry_count: # optional, default is 1
        # The timeout (seconds) to provide to requests to wait for a response.
        timeout: # optional, default is 5
        # A comma seperated links to exclude during URL checks.
        white_listed_urls: # optional, default is
        # A comma seperat
